stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./package/Dockerfile
      buildContext: .
      tag: michelia/elasticsearch:test
      registry: index.docker.io
  when:
    event:
      include:
      - push
branch: {}
